<?php require_once($_SERVER["DOCUMENT_ROOT"]."/templates/header.inc"); ?>

<div class="main_text">
    <h1>Reason 1: Very bad news for wildlife</h1>

    <p>
        Scientists are warning that plundering the seafloor with monster machines 
        risks inevitable, severe and irreversible environmental damage to our 
        oceans and marine life. You only have to look at some of the names of 
        recent research papers: ‘Deep-Sea Mining with No Net Loss of Biodiversity 
        – An Impossible Aim’.
    </p>

    <p>
        In the deep sea, we find underwater mountains that are oases for sea creatures, 
        ancient coral reefs and sharks that can live for hundreds of years. These are 
        among the longest living creatures on Earth, which makes them particularly 
        vulnerable to physical disturbance because of their slow growth rates. Researchers 
        estimate that harm to wildlife from mining “is likely to last forever on human 
        timescales”.
    </p>

    <p>
        As if the total destruction of their homes wasn’t bad enough, machines cutting the 
        seafloor will create sediment plumes, which could smother deep sea habitats for 
        kilometres. The ships on the surface for the mining operation could also release 
        toxic vapours into the water, harming many ocean species for hundreds or even 
        thousands of kilometres.
    </p>

    <p>
        And it’s not just pollution wildlife have to worry about. Noise generated by churning 
        machinery risks harming and disturbing marine mammals like whales, while floodlighting 
        areas of the dark deep ocean could cause permanent disruption to sea creatures adapted 
        to very low levels of natural light.
    </p>

    <img class="center" src="/images/content/3.jpg">
    <div class="image_description center">
        The spiral tube worm, or Sabella Spallanzanii, lives in membranous tubes, often 
        reinforced by the inclusion of mud particles and has a feathery, filter-feeding 
        crown that can be quickly withdrawn into the tube when danger threatens.<br>
        © Greenpeace / Gavin Newman
    </div>
</div>

<?php require_once($_SERVER["DOCUMENT_ROOT"]."/templates/footer.inc"); ?>