<?php 
	require_once($_SERVER["DOCUMENT_ROOT"]."/inc/vars.inc");
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?php echo $browser_title." "; ?> HOME</title>
	<link rel="stylesheet" type="text/css" href="/style/style.css">
	<link rel="stylesheet" type="text/css" href="/style/slider.css">
	<script src="/js/slider.js"></script>
</head>
<body>
	<div class="header">
		<div class="inner_wrapper">
			<div id="logo_section">
				<div id="logo_text">
					<a href="/">Avada :</a>
				</div>
			</div>
			<naw id="main_menu">
				<a href="#">
					<div class="menu_button">
						page 1
					</div>
				</a>
				<a href="#">
					<div class="menu_button">
						page 2
					</div>
				</a>
				<a href="#">
					<div class="menu_button">
						page 3
					</div>
				</a>
			</naw>
		</div>
	</div>
	<div class="content">
		<div class="inner_wrapper">